vich_uploader:
    db_driver: orm

    mappings:
        files:
            uri_prefix: /files/task
            upload_destination: '%kernel.project_dir%/public/files/task'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
